<?php
defined('BASEPATH') or exit('No direct script access allowed');
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Admin extends CI_Controller
{

    function index()
    {
    }
}
