<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Akreditasi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Akreditasi_model');
    } 

    /*
     * Listing of akreditasi
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('akreditasi/index?');
        $config['total_rows'] = $this->Akreditasi_model->get_all_akreditasi_count();
        $this->pagination->initialize($config);

        $data['akreditasi'] = $this->Akreditasi_model->get_all_akreditasi($params);
        
        $data['_view'] = 'akreditasi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new akreditasi
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('akreditasi','Akreditasi','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'akreditasi' => $this->input->post('akreditasi'),
            );
            
            $akreditasi_id = $this->Akreditasi_model->add_akreditasi($params);
            redirect('akreditasi/index');
        }
        else
        {            
            $data['_view'] = 'akreditasi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a akreditasi
     */
    function edit($akreditasi_id)
    {   
        // check if the akreditasi exists before trying to edit it
        $data['akreditasi'] = $this->Akreditasi_model->get_akreditasi($akreditasi_id);
        
        if(isset($data['akreditasi']['akreditasi_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('akreditasi','Akreditasi','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'akreditasi' => $this->input->post('akreditasi'),
                );

                $this->Akreditasi_model->update_akreditasi($akreditasi_id,$params);            
                redirect('akreditasi/index');
            }
            else
            {
                $data['_view'] = 'akreditasi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The akreditasi you are trying to edit does not exist.');
    } 

    /*
     * Deleting akreditasi
     */
    function remove($akreditasi_id)
    {
        $akreditasi = $this->Akreditasi_model->get_akreditasi($akreditasi_id);

        // check if the akreditasi exists before trying to delete it
        if(isset($akreditasi['akreditasi_id']))
        {
            $this->Akreditasi_model->delete_akreditasi($akreditasi_id);
            redirect('akreditasi/index');
        }
        else
            show_error('The akreditasi you are trying to delete does not exist.');
    }
    
}
