<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Dosen extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dosen_model');
    }

    /*
     * Listing of dosen
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('dosen/index?');
        $config['total_rows'] = $this->Dosen_model->get_all_dosen_count();
        $this->pagination->initialize($config);

        $data['dosen'] = $this->Dosen_model->get_all_dosen($params);

        $data['_view'] = 'dosen/index';
        $this->load->view('layouts/main', $data);
    }


    function view()
    {
        $NIDN = $this->session->get_userdata('NIDN');
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('dosen/view?');
        $config['total_rows'] = $this->Dosen_model->get_all_dosen_count();
        $this->pagination->initialize($config);

        $data['dosen'] = $this->Dosen_model->get_dosen($NIDN);

        $data['_view'] = 'dosen/view';

        $this->load->view('templates/auth_header', $data);
        $this->load->view('layouts/main', $data);
        $this->load->view('templates/auth_footer', $data);
    }

    /*
     * Adding a new dosen
     */
    function add()
    {
        $this->load->library('form_validation');

        $this->form_validation->set_rules('dosen_instansi', 'Dosen Instansi', 'required');
        $this->form_validation->set_rules('dosen_password', 'Dosen Password', 'required');
        $this->form_validation->set_rules('dosen_nama', 'Dosen Nama', 'required');
        $this->form_validation->set_rules('dosen_email', 'Dosen Email', 'required');
        $this->form_validation->set_rules('dosen_jeniskelamin', 'Dosen Jeniskelamin', 'required');
        $this->form_validation->set_rules('dosen_jabatanfungsional', 'Dosen Jabatanfungsional', 'required');
        $this->form_validation->set_rules('dosen_hp', 'Dosen Hp', 'required');
        $this->form_validation->set_rules('dosen_alamat', 'Dosen Alamat', 'required');
        $this->form_validation->set_rules('dosen_kodepos', 'Dosen Kodepos', 'required');
        $this->form_validation->set_rules('dosen_roles', 'Dosen Roles', 'required');

        if ($this->form_validation->run()) {
            $params = array(
                'dosen_instansi' => $this->input->post('dosen_instansi'),
                'dosen_jeniskelamin' => $this->input->post('dosen_jeniskelamin'),
                'dosen_roles' => $this->input->post('dosen_roles'),
                'dosen_aktifasi' => $this->input->post('dosen_aktifasi'),
                'dosen_password' => $this->input->post('dosen_password'),
                'dosen_nama' => $this->input->post('dosen_nama'),
                'dosen_email' => $this->input->post('dosen_email'),
                'dosen_jabatanfungsional' => $this->input->post('dosen_jabatanfungsional'),
                'dosen_hp' => $this->input->post('dosen_hp'),
                'dosen_alamat' => $this->input->post('dosen_alamat'),
                'dosen_kodepos' => $this->input->post('dosen_kodepos'),
                'dosen_s1prodi' => $this->input->post('dosen_s1prodi'),
                'dosen_s1pt' => $this->input->post('dosen_s1pt'),
                'dosen_s1tahunlulus' => $this->input->post('dosen_s1tahunlulus'),
                'dosen_s2prodi' => $this->input->post('dosen_s2prodi'),
                'dosen_s2pt' => $this->input->post('dosen_s2pt'),
                'dosen_s2tahunlulus' => $this->input->post('dosen_s2tahunlulus'),
                'dosen_s3prodi' => $this->input->post('dosen_s3prodi'),
                'dosen_s3pt' => $this->input->post('dosen_s3pt'),
                'dosen_s3tahunlulus' => $this->input->post('dosen_s3tahunlulus'),
                'dosen_profil' => $this->input->post('dosen_profil'),
            );

            $dosen_id = $this->Dosen_model->add_dosen($params);
            redirect('dosen/index');
        } else {
            $this->load->model('Frkfed_instansi_model');
            $data['all_frkfed_instansi'] = $this->Frkfed_instansi_model->get_all_frkfed_instansi();

            $this->load->model('Role_model');
            $data['all_roles'] = $this->Role_model->get_all_roles();

            $data['_view'] = 'dosen/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a dosen
     */
    function edit($NIDN)
    {
        // check if the dosen exists before trying to edit it
        $data['dosen'] = $this->Dosen_model->get_dosen($NIDN);

        if (isset($data['dosen']['NIDN'])) {
            $this->load->library('form_validation');

            $this->form_validation->set_rules('dosen_instansi', 'Dosen Instansi', 'required');
            $this->form_validation->set_rules('dosen_password', 'Dosen Password', 'required');
            $this->form_validation->set_rules('dosen_nama', 'Dosen Nama', 'required');
            $this->form_validation->set_rules('dosen_email', 'Dosen Email', 'required');
            $this->form_validation->set_rules('dosen_jeniskelamin', 'Dosen Jeniskelamin', 'required');
            $this->form_validation->set_rules('dosen_jabatanfungsional', 'Dosen Jabatanfungsional', 'required');
            $this->form_validation->set_rules('dosen_hp', 'Dosen Hp', 'required');
            $this->form_validation->set_rules('dosen_alamat', 'Dosen Alamat', 'required');
            $this->form_validation->set_rules('dosen_kodepos', 'Dosen Kodepos', 'required');
            $this->form_validation->set_rules('dosen_roles', 'Dosen Roles', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'dosen_instansi' => $this->input->post('dosen_instansi'),
                    'dosen_jeniskelamin' => $this->input->post('dosen_jeniskelamin'),
                    'dosen_roles' => $this->input->post('dosen_roles'),
                    'dosen_aktifasi' => $this->input->post('dosen_aktifasi'),
                    'dosen_password' => $this->input->post('dosen_password'),
                    'dosen_nama' => $this->input->post('dosen_nama'),
                    'dosen_email' => $this->input->post('dosen_email'),
                    'dosen_jabatanfungsional' => $this->input->post('dosen_jabatanfungsional'),
                    'dosen_hp' => $this->input->post('dosen_hp'),
                    'dosen_alamat' => $this->input->post('dosen_alamat'),
                    'dosen_kodepos' => $this->input->post('dosen_kodepos'),
                    'dosen_s1prodi' => $this->input->post('dosen_s1prodi'),
                    'dosen_s1pt' => $this->input->post('dosen_s1pt'),
                    'dosen_s1tahunlulus' => $this->input->post('dosen_s1tahunlulus'),
                    'dosen_s2prodi' => $this->input->post('dosen_s2prodi'),
                    'dosen_s2pt' => $this->input->post('dosen_s2pt'),
                    'dosen_s2tahunlulus' => $this->input->post('dosen_s2tahunlulus'),
                    'dosen_s3prodi' => $this->input->post('dosen_s3prodi'),
                    'dosen_s3pt' => $this->input->post('dosen_s3pt'),
                    'dosen_s3tahunlulus' => $this->input->post('dosen_s3tahunlulus'),
                    'dosen_profil' => $this->input->post('dosen_profil'),
                );

                $this->Dosen_model->update_dosen($NIDN, $params);
                redirect('dosen/index');
            } else {
                $this->load->model('Frkfed_instansi_model');
                $data['all_frkfed_instansi'] = $this->Frkfed_instansi_model->get_all_frkfed_instansi();

                $this->load->model('Role_model');
                $data['all_roles'] = $this->Role_model->get_all_roles();

                $data['_view'] = 'dosen/edit';
                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The dosen you are trying to edit does not exist.');
    }

    /*
     * Deleting dosen
     */
    function remove($NIDN)
    {
        $dosen = $this->Dosen_model->get_dosen($NIDN);

        // check if the dosen exists before trying to delete it
        if (isset($dosen['NIDN'])) {
            $this->Dosen_model->delete_dosen($NIDN);
            redirect('dosen/index');
        } else
            show_error('The dosen you are trying to delete does not exist.');
    }
}
