<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fakultas extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fakultas_model');
    } 

    /*
     * Listing of fakultas
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('fakultas/index?');
        $config['total_rows'] = $this->Fakultas_model->get_all_fakultas_count();
        $this->pagination->initialize($config);

        $data['fakultas'] = $this->Fakultas_model->get_all_fakultas($params);
        
        $data['_view'] = 'fakultas/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fakultas
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('fakultas_nama','Fakultas Nama','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'fakultas_nama' => $this->input->post('fakultas_nama'),
            );
            
            $fakultas_id = $this->Fakultas_model->add_fakultas($params);
            redirect('fakultas/index');
        }
        else
        {            
            $data['_view'] = 'fakultas/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fakultas
     */
    function edit($fakultas_kode)
    {   
        // check if the fakultas exists before trying to edit it
        $data['fakultas'] = $this->Fakultas_model->get_fakultas($fakultas_kode);
        
        if(isset($data['fakultas']['fakultas_kode']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('fakultas_nama','Fakultas Nama','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'fakultas_nama' => $this->input->post('fakultas_nama'),
                );

                $this->Fakultas_model->update_fakultas($fakultas_kode,$params);            
                redirect('fakultas/index');
            }
            else
            {
                $data['_view'] = 'fakultas/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fakultas you are trying to edit does not exist.');
    } 

    /*
     * Deleting fakultas
     */
    function remove($fakultas_kode)
    {
        $fakultas = $this->Fakultas_model->get_fakultas($fakultas_kode);

        // check if the fakultas exists before trying to delete it
        if(isset($fakultas['fakultas_kode']))
        {
            $this->Fakultas_model->delete_fakultas($fakultas_kode);
            redirect('fakultas/index');
        }
        else
            show_error('The fakultas you are trying to delete does not exist.');
    }
    
}