<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fed extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fed_model');
    } 

    /*
     * Listing of fed
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('fed/index?');
        $config['total_rows'] = $this->Fed_model->get_all_fed_count();
        $this->pagination->initialize($config);

        $data['fed'] = $this->Fed_model->get_all_fed($params);
        
        $data['_view'] = 'fed/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fed
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('fed_tahun','Fed Tahun','required');
		$this->form_validation->set_rules('fed_semester','Fed Semester','required');
		$this->form_validation->set_rules('fed_frk_id','Fed Frk Id','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'fed_frk_id' => $this->input->post('fed_frk_id'),
				'fed_tahun' => $this->input->post('fed_tahun'),
				'fed_semester' => $this->input->post('fed_semester'),
				'fed_status' => $this->input->post('fed_status'),
				'fed_ak' => $this->input->post('fed_ak'),
				'fed_kuan' => $this->input->post('fed_kuan'),
				'fed_kual' => $this->input->post('fed_kual'),
				'fed_waktu' => $this->input->post('fed_waktu'),
				'fed_biaya' => $this->input->post('fed_biaya'),
				'fed_skp' => $this->input->post('fed_skp'),
            );
            
            $fed_id = $this->Fed_model->add_fed($params);
            redirect('fed/index');
        }
        else
        {
			$this->load->model('Frk_model');
			$data['all_frk'] = $this->Frk_model->get_all_frk();
			$data['all_frk'] = $this->Frk_model->get_all_frk();
			$data['all_frk'] = $this->Frk_model->get_all_frk();
            
            $data['_view'] = 'fed/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fed
     */
    function edit($fed_id)
    {   
        // check if the fed exists before trying to edit it
        $data['fed'] = $this->Fed_model->get_fed($fed_id);
        
        if(isset($data['fed']['fed_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('fed_tahun','Fed Tahun','required');
			$this->form_validation->set_rules('fed_semester','Fed Semester','required');
			$this->form_validation->set_rules('fed_frk_id','Fed Frk Id','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'fed_frk_id' => $this->input->post('fed_frk_id'),
					'fed_tahun' => $this->input->post('fed_tahun'),
					'fed_semester' => $this->input->post('fed_semester'),
					'fed_status' => $this->input->post('fed_status'),
					'fed_ak' => $this->input->post('fed_ak'),
					'fed_kuan' => $this->input->post('fed_kuan'),
					'fed_kual' => $this->input->post('fed_kual'),
					'fed_waktu' => $this->input->post('fed_waktu'),
					'fed_biaya' => $this->input->post('fed_biaya'),
					'fed_skp' => $this->input->post('fed_skp'),
                );

                $this->Fed_model->update_fed($fed_id,$params);            
                redirect('fed/index');
            }
            else
            {
				$this->load->model('Frk_model');
				$data['all_frk'] = $this->Frk_model->get_all_frk();
				$data['all_frk'] = $this->Frk_model->get_all_frk();
				$data['all_frk'] = $this->Frk_model->get_all_frk();

                $data['_view'] = 'fed/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fed you are trying to edit does not exist.');
    } 

    /*
     * Deleting fed
     */
    function remove($fed_id)
    {
        $fed = $this->Fed_model->get_fed($fed_id);

        // check if the fed exists before trying to delete it
        if(isset($fed['fed_id']))
        {
            $this->Fed_model->delete_fed($fed_id);
            redirect('fed/index');
        }
        else
            show_error('The fed you are trying to delete does not exist.');
    }
    
}
