<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Frkfed_jenis extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Frkfed_jenis_model');
    } 

    /*
     * Listing of frkfed_jenis
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('frkfed_jenis/index?');
        $config['total_rows'] = $this->Frkfed_jenis_model->get_all_frkfed_jenis_count();
        $this->pagination->initialize($config);

        $data['frkfed_jenis'] = $this->Frkfed_jenis_model->get_all_frkfed_jenis($params);
        
        $data['_view'] = 'frkfed_jenis/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new frkfed_jenis
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('frkfed_kategori','Frkfed Kategori','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'frkfed_kategori' => $this->input->post('frkfed_kategori'),
            );
            
            $frkfed_jenis_id = $this->Frkfed_jenis_model->add_frkfed_jenis($params);
            redirect('frkfed_jenis/index');
        }
        else
        {            
            $data['_view'] = 'frkfed_jenis/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a frkfed_jenis
     */
    function edit($frkfed_id)
    {   
        // check if the frkfed_jenis exists before trying to edit it
        $data['frkfed_jenis'] = $this->Frkfed_jenis_model->get_frkfed_jenis($frkfed_id);
        
        if(isset($data['frkfed_jenis']['frkfed_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('frkfed_kategori','Frkfed Kategori','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'frkfed_kategori' => $this->input->post('frkfed_kategori'),
                );

                $this->Frkfed_jenis_model->update_frkfed_jenis($frkfed_id,$params);            
                redirect('frkfed_jenis/index');
            }
            else
            {
                $data['_view'] = 'frkfed_jenis/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The frkfed_jenis you are trying to edit does not exist.');
    } 

    /*
     * Deleting frkfed_jenis
     */
    function remove($frkfed_id)
    {
        $frkfed_jenis = $this->Frkfed_jenis_model->get_frkfed_jenis($frkfed_id);

        // check if the frkfed_jenis exists before trying to delete it
        if(isset($frkfed_jenis['frkfed_id']))
        {
            $this->Frkfed_jenis_model->delete_frkfed_jenis($frkfed_id);
            redirect('frkfed_jenis/index');
        }
        else
            show_error('The frkfed_jenis you are trying to delete does not exist.');
    }
    
}
