<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Frkfed_instansi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Frkfed_instansi_model');
    } 

    /*
     * Listing of frkfed_instansi
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('frkfed_instansi/index?');
        $config['total_rows'] = $this->Frkfed_instansi_model->get_all_frkfed_instansi_count();
        $this->pagination->initialize($config);

        $data['frkfed_instansi'] = $this->Frkfed_instansi_model->get_all_frkfed_instansi($params);
        
        $data['_view'] = 'frkfed_instansi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new frkfed_instansi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'instansi_pt' => $this->input->post('instansi_pt'),
				'instansi_fakultas' => $this->input->post('instansi_fakultas'),
				'instansi_prodi' => $this->input->post('instansi_prodi'),
				'instansi_logo' => $this->input->post('instansi_logo'),
            );
            
            $frkfed_instansi_id = $this->Frkfed_instansi_model->add_frkfed_instansi($params);
            redirect('frkfed_instansi/index');
        }
        else
        {
			$this->load->model('Perguruan_tinggi_model');
			$data['all_perguruan_tinggi'] = $this->Perguruan_tinggi_model->get_all_perguruan_tinggi();

			$this->load->model('Fakultas_model');
			$data['all_fakultas'] = $this->Fakultas_model->get_all_fakultas();

			$this->load->model('Prodi_model');
			$data['all_prodi'] = $this->Prodi_model->get_all_prodi();
            
            $data['_view'] = 'frkfed_instansi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a frkfed_instansi
     */
    function edit($instansi_id)
    {   
        // check if the frkfed_instansi exists before trying to edit it
        $data['frkfed_instansi'] = $this->Frkfed_instansi_model->get_frkfed_instansi($instansi_id);
        
        if(isset($data['frkfed_instansi']['instansi_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'instansi_pt' => $this->input->post('instansi_pt'),
					'instansi_fakultas' => $this->input->post('instansi_fakultas'),
					'instansi_prodi' => $this->input->post('instansi_prodi'),
					'instansi_logo' => $this->input->post('instansi_logo'),
                );

                $this->Frkfed_instansi_model->update_frkfed_instansi($instansi_id,$params);            
                redirect('frkfed_instansi/index');
            }
            else
            {
				$this->load->model('Perguruan_tinggi_model');
				$data['all_perguruan_tinggi'] = $this->Perguruan_tinggi_model->get_all_perguruan_tinggi();

				$this->load->model('Fakultas_model');
				$data['all_fakultas'] = $this->Fakultas_model->get_all_fakultas();

				$this->load->model('Prodi_model');
				$data['all_prodi'] = $this->Prodi_model->get_all_prodi();

                $data['_view'] = 'frkfed_instansi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The frkfed_instansi you are trying to edit does not exist.');
    } 

    /*
     * Deleting frkfed_instansi
     */
    function remove($instansi_id)
    {
        $frkfed_instansi = $this->Frkfed_instansi_model->get_frkfed_instansi($instansi_id);

        // check if the frkfed_instansi exists before trying to delete it
        if(isset($frkfed_instansi['instansi_id']))
        {
            $this->Frkfed_instansi_model->delete_frkfed_instansi($instansi_id);
            redirect('frkfed_instansi/index');
        }
        else
            show_error('The frkfed_instansi you are trying to delete does not exist.');
    }
    
}
