<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perguruan_tinggi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Perguruan_tinggi_model');
    } 

    /*
     * Listing of perguruan_tinggi
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('perguruan_tinggi/index?');
        $config['total_rows'] = $this->Perguruan_tinggi_model->get_all_perguruan_tinggi_count();
        $this->pagination->initialize($config);

        $data['perguruan_tinggi'] = $this->Perguruan_tinggi_model->get_all_perguruan_tinggi($params);
        
        $data['_view'] = 'perguruan_tinggi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new perguruan_tinggi
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('pt_nama','Pt Nama','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'pt_akreditasi_id' => $this->input->post('pt_akreditasi_id'),
				'pt_nama' => $this->input->post('pt_nama'),
				'pt_alamat' => $this->input->post('pt_alamat'),
				'pt_website' => $this->input->post('pt_website'),
            );
            
            $perguruan_tinggi_id = $this->Perguruan_tinggi_model->add_perguruan_tinggi($params);
            redirect('perguruan_tinggi/index');
        }
        else
        {
			$this->load->model('Akreditasi_model');
			$data['all_akreditasi'] = $this->Akreditasi_model->get_all_akreditasi();
            
            $data['_view'] = 'perguruan_tinggi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a perguruan_tinggi
     */
    function edit($pt_id)
    {   
        // check if the perguruan_tinggi exists before trying to edit it
        $data['perguruan_tinggi'] = $this->Perguruan_tinggi_model->get_perguruan_tinggi($pt_id);
        
        if(isset($data['perguruan_tinggi']['pt_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('pt_nama','Pt Nama','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'pt_akreditasi_id' => $this->input->post('pt_akreditasi_id'),
					'pt_nama' => $this->input->post('pt_nama'),
					'pt_alamat' => $this->input->post('pt_alamat'),
					'pt_website' => $this->input->post('pt_website'),
                );

                $this->Perguruan_tinggi_model->update_perguruan_tinggi($pt_id,$params);            
                redirect('perguruan_tinggi/index');
            }
            else
            {
				$this->load->model('Akreditasi_model');
				$data['all_akreditasi'] = $this->Akreditasi_model->get_all_akreditasi();

                $data['_view'] = 'perguruan_tinggi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The perguruan_tinggi you are trying to edit does not exist.');
    } 

    /*
     * Deleting perguruan_tinggi
     */
    function remove($pt_id)
    {
        $perguruan_tinggi = $this->Perguruan_tinggi_model->get_perguruan_tinggi($pt_id);

        // check if the perguruan_tinggi exists before trying to delete it
        if(isset($perguruan_tinggi['pt_id']))
        {
            $this->Perguruan_tinggi_model->delete_perguruan_tinggi($pt_id);
            redirect('perguruan_tinggi/index');
        }
        else
            show_error('The perguruan_tinggi you are trying to delete does not exist.');
    }
    
}
