<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Prodi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Prodi_model');
    } 

    /*
     * Listing of prodi
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('prodi/index?');
        $config['total_rows'] = $this->Prodi_model->get_all_prodi_count();
        $this->pagination->initialize($config);

        $data['prodi'] = $this->Prodi_model->get_all_prodi($params);
        
        $data['_view'] = 'prodi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new prodi
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('prodi_nama','Prodi Nama','required');
		$this->form_validation->set_rules('prodi_akreditasi','Prodi Akreditasi','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'prodi_akreditasi' => $this->input->post('prodi_akreditasi'),
				'prodi_nama' => $this->input->post('prodi_nama'),
            );
            
            $prodi_id = $this->Prodi_model->add_prodi($params);
            redirect('prodi/index');
        }
        else
        {
			$this->load->model('Akreditasi_model');
			$data['all_akreditasi'] = $this->Akreditasi_model->get_all_akreditasi();
            
            $data['_view'] = 'prodi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a prodi
     */
    function edit($prodi_kode)
    {   
        // check if the prodi exists before trying to edit it
        $data['prodi'] = $this->Prodi_model->get_prodi($prodi_kode);
        
        if(isset($data['prodi']['prodi_kode']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('prodi_nama','Prodi Nama','required');
			$this->form_validation->set_rules('prodi_akreditasi','Prodi Akreditasi','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'prodi_akreditasi' => $this->input->post('prodi_akreditasi'),
					'prodi_nama' => $this->input->post('prodi_nama'),
                );

                $this->Prodi_model->update_prodi($prodi_kode,$params);            
                redirect('prodi/index');
            }
            else
            {
				$this->load->model('Akreditasi_model');
				$data['all_akreditasi'] = $this->Akreditasi_model->get_all_akreditasi();

                $data['_view'] = 'prodi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The prodi you are trying to edit does not exist.');
    } 

    /*
     * Deleting prodi
     */
    function remove($prodi_kode)
    {
        $prodi = $this->Prodi_model->get_prodi($prodi_kode);

        // check if the prodi exists before trying to delete it
        if(isset($prodi['prodi_kode']))
        {
            $this->Prodi_model->delete_prodi($prodi_kode);
            redirect('prodi/index');
        }
        else
            show_error('The prodi you are trying to delete does not exist.');
    }
    
}
