<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Role extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Role_model');
    } 

    /*
     * Listing of roles
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('role/index?');
        $config['total_rows'] = $this->Role_model->get_all_roles_count();
        $this->pagination->initialize($config);

        $data['roles'] = $this->Role_model->get_all_roles($params);
        
        $data['_view'] = 'role/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new role
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('roles_nama','Roles Nama','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'roles_nama' => $this->input->post('roles_nama'),
            );
            
            $role_id = $this->Role_model->add_role($params);
            redirect('role/index');
        }
        else
        {            
            $data['_view'] = 'role/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a role
     */
    function edit($roles_id)
    {   
        // check if the role exists before trying to edit it
        $data['role'] = $this->Role_model->get_role($roles_id);
        
        if(isset($data['role']['roles_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('roles_nama','Roles Nama','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'roles_nama' => $this->input->post('roles_nama'),
                );

                $this->Role_model->update_role($roles_id,$params);            
                redirect('role/index');
            }
            else
            {
                $data['_view'] = 'role/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The role you are trying to edit does not exist.');
    } 

    /*
     * Deleting role
     */
    function remove($roles_id)
    {
        $role = $this->Role_model->get_role($roles_id);

        // check if the role exists before trying to delete it
        if(isset($role['roles_id']))
        {
            $this->Role_model->delete_role($roles_id);
            redirect('role/index');
        }
        else
            show_error('The role you are trying to delete does not exist.');
    }
    
}
