<?php
defined('BASEPATH') or exit('No direct script access allowed');
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class User extends CI_Controller
{

    function index()
    {
        $data['title'] = 'Dashboard - FRK / FED';
        $data['user'] = $this->db->get_where('dosen', ['NIDN' => $this->session->userdata('NIDN')])->row_array();
        $data['text'] = 'Selamat Datang, ' . $data['user']['dosen_nama'];

        $this->load->view('templates/user_header', $data);
        $this->load->view('user/index', $data);
        $this->load->view('templates/user_footer', $data);
    }
}
