<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Akreditasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get akreditasi by akreditasi_id
     */
    function get_akreditasi($akreditasi_id)
    {
        return $this->db->get_where('akreditasi',array('akreditasi_id'=>$akreditasi_id))->row_array();
    }
    
    /*
     * Get all akreditasi count
     */
    function get_all_akreditasi_count()
    {
        $this->db->from('akreditasi');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all akreditasi
     */
    function get_all_akreditasi($params = array())
    {
        $this->db->order_by('akreditasi_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('akreditasi')->result_array();
    }
        
    /*
     * function to add new akreditasi
     */
    function add_akreditasi($params)
    {
        $this->db->insert('akreditasi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update akreditasi
     */
    function update_akreditasi($akreditasi_id,$params)
    {
        $this->db->where('akreditasi_id',$akreditasi_id);
        return $this->db->update('akreditasi',$params);
    }
    
    /*
     * function to delete akreditasi
     */
    function delete_akreditasi($akreditasi_id)
    {
        return $this->db->delete('akreditasi',array('akreditasi_id'=>$akreditasi_id));
    }
}
