<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fed_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fed by fed_id
     */
    function get_fed($fed_id)
    {
        return $this->db->get_where('fed',array('fed_id'=>$fed_id))->row_array();
    }
    
    /*
     * Get all fed count
     */
    function get_all_fed_count()
    {
        $this->db->from('fed');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all fed
     */
    function get_all_fed($params = array())
    {
        $this->db->order_by('fed_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('fed')->result_array();
    }
        
    /*
     * function to add new fed
     */
    function add_fed($params)
    {
        $this->db->insert('fed',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fed
     */
    function update_fed($fed_id,$params)
    {
        $this->db->where('fed_id',$fed_id);
        return $this->db->update('fed',$params);
    }
    
    /*
     * function to delete fed
     */
    function delete_fed($fed_id)
    {
        return $this->db->delete('fed',array('fed_id'=>$fed_id));
    }
}
