<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Frk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get frk by frk_id
     */
    function get_frk($frk_id)
    {
        return $this->db->get_where('frk',array('frk_id'=>$frk_id))->row_array();
    }
    
    /*
     * Get all frk count
     */
    function get_all_frk_count()
    {
        $this->db->from('frk');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all frk
     */
    function get_all_frk($params = array())
    {
        $this->db->order_by('frk_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('frk')->result_array();
    }
        
    /*
     * function to add new frk
     */
    function add_frk($params)
    {
        $this->db->insert('frk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update frk
     */
    function update_frk($frk_id,$params)
    {
        $this->db->where('frk_id',$frk_id);
        return $this->db->update('frk',$params);
    }
    
    /*
     * function to delete frk
     */
    function delete_frk($frk_id)
    {
        return $this->db->delete('frk',array('frk_id'=>$frk_id));
    }
}
