<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Frkfed_jenis_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get frkfed_jenis by frkfed_id
     */
    function get_frkfed_jenis($frkfed_id)
    {
        return $this->db->get_where('frkfed_jenis',array('frkfed_id'=>$frkfed_id))->row_array();
    }
    
    /*
     * Get all frkfed_jenis count
     */
    function get_all_frkfed_jenis_count()
    {
        $this->db->from('frkfed_jenis');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all frkfed_jenis
     */
    function get_all_frkfed_jenis($params = array())
    {
        $this->db->order_by('frkfed_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('frkfed_jenis')->result_array();
    }
        
    /*
     * function to add new frkfed_jenis
     */
    function add_frkfed_jenis($params)
    {
        $this->db->insert('frkfed_jenis',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update frkfed_jenis
     */
    function update_frkfed_jenis($frkfed_id,$params)
    {
        $this->db->where('frkfed_id',$frkfed_id);
        return $this->db->update('frkfed_jenis',$params);
    }
    
    /*
     * function to delete frkfed_jenis
     */
    function delete_frkfed_jenis($frkfed_id)
    {
        return $this->db->delete('frkfed_jenis',array('frkfed_id'=>$frkfed_id));
    }
}
