<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Matakuliah_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get matakuliah by matakuliah_id
     */
    function get_matakuliah($matakuliah_id)
    {
        return $this->db->get_where('matakuliah',array('matakuliah_id'=>$matakuliah_id))->row_array();
    }
    
    /*
     * Get all matakuliah count
     */
    function get_all_matakuliah_count()
    {
        $this->db->from('matakuliah');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all matakuliah
     */
    function get_all_matakuliah($params = array())
    {
        $this->db->order_by('matakuliah_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('matakuliah')->result_array();
    }
        
    /*
     * function to add new matakuliah
     */
    function add_matakuliah($params)
    {
        $this->db->insert('matakuliah',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update matakuliah
     */
    function update_matakuliah($matakuliah_id,$params)
    {
        $this->db->where('matakuliah_id',$matakuliah_id);
        return $this->db->update('matakuliah',$params);
    }
    
    /*
     * function to delete matakuliah
     */
    function delete_matakuliah($matakuliah_id)
    {
        return $this->db->delete('matakuliah',array('matakuliah_id'=>$matakuliah_id));
    }
}
