<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Perguruan_tinggi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get perguruan_tinggi by pt_id
     */
    function get_perguruan_tinggi($pt_id)
    {
        return $this->db->get_where('perguruan_tinggi',array('pt_id'=>$pt_id))->row_array();
    }
    
    /*
     * Get all perguruan_tinggi count
     */
    function get_all_perguruan_tinggi_count()
    {
        $this->db->from('perguruan_tinggi');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all perguruan_tinggi
     */
    function get_all_perguruan_tinggi($params = array())
    {
        $this->db->order_by('pt_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('perguruan_tinggi')->result_array();
    }
        
    /*
     * function to add new perguruan_tinggi
     */
    function add_perguruan_tinggi($params)
    {
        $this->db->insert('perguruan_tinggi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update perguruan_tinggi
     */
    function update_perguruan_tinggi($pt_id,$params)
    {
        $this->db->where('pt_id',$pt_id);
        return $this->db->update('perguruan_tinggi',$params);
    }
    
    /*
     * function to delete perguruan_tinggi
     */
    function delete_perguruan_tinggi($pt_id)
    {
        return $this->db->delete('perguruan_tinggi',array('pt_id'=>$pt_id));
    }
}
