<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Prodi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get prodi by prodi_kode
     */
    function get_prodi($prodi_kode)
    {
        return $this->db->get_where('prodi',array('prodi_kode'=>$prodi_kode))->row_array();
    }
    
    /*
     * Get all prodi count
     */
    function get_all_prodi_count()
    {
        $this->db->from('prodi');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all prodi
     */
    function get_all_prodi($params = array())
    {
        $this->db->order_by('prodi_kode', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('prodi')->result_array();
    }
        
    /*
     * function to add new prodi
     */
    function add_prodi($params)
    {
        $this->db->insert('prodi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update prodi
     */
    function update_prodi($prodi_kode,$params)
    {
        $this->db->where('prodi_kode',$prodi_kode);
        return $this->db->update('prodi',$params);
    }
    
    /*
     * function to delete prodi
     */
    function delete_prodi($prodi_kode)
    {
        return $this->db->delete('prodi',array('prodi_kode'=>$prodi_kode));
    }
}
